#! /usr/bin/env bash

# Grab our work directory and make a temp directory for working in
BASEDIR=$(cd "$(dirname "$0")" && pwd)
WORKDIR=`mktemp -d -p "$BASEDIR"`
if [[ ! "$WORKDIR" || ! -d "$WORKDIR" ]]; then
  echo "Could not create temp directory"
  exit 1
fi

# On exit, cleanup the temp directory
function cleanup() {
  rm -rf "$WORKDIR"
}
trap cleanup EXIT

function unset_windows_path() {
  if [[ ! -z "$WSL_DISTRO_NAME" && ! -f /etc/wsl.conf ]]; then
    echo "Turning off WSL path integration"
    echo "You will need to restart the WSL environment by executing"
    echo " wsl --shutdown or wsl -t \"$WSL_DISTRO_NAME\" in the host OS"
    sudo cp etc/wsl.conf /etc
  fi
}

# Install everything listed in the os-packages file
function install_os_packages() {
  if $(which apt >/dev/null 2>&1); then
    echo "Installing APT packages:"
    sudo apt -y -qq update
    sudo apt -y -qq install $(xargs -a "$BASEDIR/packages/apt")
  elif $(which dnf > /dev/null 2>&1); then
    local ARCH=$(uname -i)
    echo "Installing DNF/YUM packages:"
    sudo -- sh \
      -c 'dnf config-manager --set-enabled PowerTools || dnf config-manager --set-enabled ol8_codeready_builder'
    sudo dnf -y install $(yum -q search epel | grep "$ARCH" | cut -f 1 -d .)
    sudo dnf -y install $(xargs -a "$BASEDIR/packages/yum")
  fi
}

# Symlink everything in home to a corresponding dotfile in the home directory
function install_dotfiles() {
  local DOTSDIR="$BASEDIR/home"
  for DOTPATH in $DOTSDIR/*; do
    local DOTFILE="$HOME/.$(basename "$DOTPATH")"
    echo "Linking $DOTFILE => $DOTPATH"
    rm -f $DOTFILE
    ln -sf $DOTPATH $DOTFILE
  done
  rm -f $HOME/.zprofile
  ln -sf $HOME/.profile $HOME/.zprofile
}

# Set up .config for nvim
function install_config() {
  local CONFIGDIR="$BASEDIR/config"
  for SRC in $(find $CONFIGDIR -type f); do
    local DEST=${SRC/$CONFIGDIR/$HOME\/.config}
    echo "Linking $DEST => $SRC"
    mkdir -p $(dirname $DEST)
    ln -sf $SRC $DEST
  done
}

function run_scriptlets() {
  SCRIPTLETS="$BASEDIR/scriptlets"
  for SCRIPLET in $(find $SCRIPTLETS -executable -type f); do
     $SCRIPLET "$WORKDIR"
  done
}

unset_windows_path
install_os_packages
install_dotfiles
install_config
run_scriptlets
