#! /usr/bin/env bash
# Install Oh my Zsh and plugins

########################
ZSHPATH=$(which zsh)
if [ "$SHELL" != "$ZSHPATH" ]; then
  echo "Changing shell to zsh"
  chsh -s "$ZSHPATH"
fi

########################
OMZINSTALLER="https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh"
OMZDIR="$HOME/.oh-my-zsh"

if [ ! -d "$OMZDIR" ]; then
  echo "Installing oh my zsh"
  sh -c "$(wget $OMZINSTALLER -O -)" -- install.sh --keep-zshrc --unattended
fi

OMZCUSTOM="$OMZDIR/custom"

NVMINSTALLER="https://github.com/lukechilds/zsh-nvm"
NVMDEST="$OMZCUSTOM/plugins/zsh-nvm"
if [ ! -d "$NVMDEST" ]; then
  echo "Installing zsh-nvm"
  git clone "$NVMINSTALLER" "$NVMDEST"
fi

P10KINSTALLER="https://github.com/romkatv/powerlevel10k.git"
P10KDEST="$OMZCUSTOM/themes/powerlevel10k"
if [ ! -d "$P10KDEST" ]; then
  echo "Installing p10k"
  git clone --depth=1 "$P10KINSTALLER" "$P10KDEST"
fi
