#! /usr/bin/env bash
# Install RVM

RUBYVER="3.2"

if [ ! -d ~/.rvm ]; then
  gpg2 --keyserver keyserver.ubuntu.com \
    --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 \
                7D2BAF1CF37B13E2069D6956105BD0E739499BDB
  curl -sSL https://get.rvm.io | bash -s head --ruby=$RUBYVER
fi
