#!/bin/env bash

AWSCLI_URI="https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
TMP_PATH=`mktemp -d`
function cleanup() {
  rm -rf "$TMP_PATH"
}
trap cleanup EXIT

if ! command -v aws > /dev/null; then
  echo "Installing AWS CLI"
  mkdir -p "$HOME/.local/bin"

  cd $TMP_PATH
  curl -fsSL "$AWSCLI_URI" -o awscliv2.zip
  unzip awscliv2.zip
  ./aws/install -i "$HOME/.local/aws-cli" -b "$HOME/.local/bin"
fi
