#! /usr/bin/env bash
# Install AWS Elastic Beanstalk CLI

REPO="https://github.com/aws/aws-elastic-beanstalk-cli-setup"
DEST="$1/ebcli"

if ! command -v eb &> /dev/null; then
  echo "Installing ebcli"
  git clone "$REPO" "$DEST"
  sh -c "cd $DEST && python3 scripts/ebcli_installer.py"
  mkdir -p ~/.local/bin && ln -sf $HOME/.ebcli-virtual-env/bin/eb $HOME/.local/bin/eb
fi
