#! /usr/bin/env bash
# Generate a key pair for API authentication against OCI
OCI=$HOME/.oci
KEY=$OCI/terraform.pem
PUB=$OCI/terraform_public.pem

mkdir -p $OCI && chmod 700 $OCI
[ ! -f $KEY ] && openssl genrsa -out $KEY
[ ! -f $PUB ] && openssl rsa -pubout -in $KEY -out $PUB
echo "Public key for Oracle Cloud API access from this machine"
cat $PUB
echo "See https://docs.oracle.com/en-us/iaas/developer-tutorials/tutorials/tf-provider/01-summary.htm"
