#!/bin/env bash
KEY_URI=https://dl.google.com/linux/linux_signing_key.pub
DEB_URI=https://dl.google.com/linux/chrome/deb/

KEY_FILE=/etc/apt/keyrings/google-chrome.gpg
LIST_FILE=/etc/apt/sources.list.d/google-chrome.list

DEB_LINE="deb [signed-by=$KEY_FILE] $DEB_URI stable main"


if [ ! -f "$LIST_FILE" ]; then
    echo "Adding Google Chrome APT repository at $LIST_FILE"
    curl -fsSL "$KEY_URI" | sudo gpg --no-tty --batch --dearmor -o "$KEY_FILE"
    echo "$DEB_LINE" | sudo tee $LIST_FILE > /dev/null
    sudo chmod 644 "$KEY_FILE" "$LIST_FILE"
    sudo apt -qq update
fi

sudo apt -qq -y install google-chrome-stable
